name: "Build ImmortalWrt Installer 24.10.2-ext4 ISO"

on:
 workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checking out git repository"
        # 【优化】使用更新的 action 版本
        uses: actions/checkout@v4
      
      - name: "Set executable permissions"
        run: |
          chmod +x ${{ github.workspace }}/imm-ext4.sh
          chmod +x ${{ github.workspace }}/supportFiles/immortalwrt/build-ext4.sh

      - name: "Build Image"
        run: ./imm-ext4.sh
      
      - name: "Publish"
        # 【优化】使用更新的 action 版本
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "ImmortalWrt-Installer-x86_64-ISO"
          body_path: ${{ github.workspace }}/supportFiles/immortalwrt/info.md
          files: |
            output/immortalwrt-installer-generic-ext4-combined-x86_64.iso
          token: ${{ secrets.GITHUB_TOKEN }}
